name: Plugin assets/readme update
on:
  push:
    branches:
    - master
    paths:
    - 'readme.txt'
    - '.wordpress-org/**'
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress.org plugin assets/readme update
      uses: wearerequired/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: fs-disable-users
